# Generated by Django 4.1 on 2022-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=30)),
                ('plate', models.IntegerField()),
                ('image', models.ImageField(upload_to='cars_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
